### ISSUE TITLE
[BUG] Square Payments is unable to authorize

### ISSUE THREAD

**Issue by ThePoShWolf** [microsoft/PowerPlatformConnectors#1872]
### Type of Connector

Independent Publisher Connector

### Name of Connector

Square Payments

### Describe the bug

I created a Logic App workflow and added in a Square Payments action. When I attempt to authorize myself, I'm met with the following error:

![image](https://user-images.githubusercontent.com/30065933/183315178-4dba49d3-306e-4752-9c65-afb7317c781c.png)

Here is the full url:

```
https://squareupsandbox.com/oauth2/authorize?client_id=sq0idp-bjhfropQ5DM7gobOrHkHUA&response_type=code&redirect_uri=https%3a%2f%2fglobal.consent.azure-apim.net%2fredirect&scope=&state=459f5c37-c7bc-4cf4-b5ae-430ba31c4514_logic-apis-westus2_azure-apim.net
```

You'll notice that it is also pointed at the sandbox URL.

For what its worth, I did try using the production URL and replacing the Client ID with my own, but I was still met with an error:

```
Failed with error: 'OAuth2 authorization flow failed for service 'Generic Oauth 2'. OAuth 2 sign in failed to exchange code for access token. Client ID and secret sent in form body.. Response status code=Unauthorized. Response body: { "message": "Not Authorized", "type": "service.not_authorized" } Client ID and secret sent in Basic authorization header.. Response status code=BadRequest. Response body: { "message": "missing required parameter 'client_id'", "type": "bad_request.missing_parameter" } '. Please sign in again.
```

### Is this a security bug?

No, this is not a security bug

### What is the severity of this bug?

Severity 1 - Connector is broken or there's a very serious issue

### To Reproduce

This is very simple to reproduce (at least in a Logic App):

1. Create a workflow
2. Add a Square Payments action (and don't already have an existing connection)
3. Click on the Sign In button in that new action.

### Expected behavior

I would expect to be presented with a Square login screen and then be able to sign into my Square account and be able to use the connector.

### Environment summary

Azure Logic Apps

### Additional context

I'll tag @troystaylor since he is the author of this connector.

Thanks!

**Comment by troystaylor** [comment]
Thank you, Anthony, for alerting me to this issue. Let me check with the deployed files and recreate a login. Expect a fix to be submitted within the next few days.

**Comment by ThePoShWolf** [comment]
No problem! Thanks for the quick response and for the other connectors that you've released. Your work has made mine a lot easier 😃

**Comment by troystaylor** [comment]
This should be resolved with this PR: https://github.com/microsoft/PowerPlatformConnectors/pull/1878

**Comment by ThePoShWolf** [comment]
@troystaylor I saw that the PR was merged 3 days ago, but I'm still getting an error when trying to authenticate the Square Payments connector in a Logic App:

![image](https://user-images.githubusercontent.com/30065933/188343377-a0d9282c-4b31-4588-a4af-d2dbefc0c2e7.png)

Is it supposed to be pointed at the sandbox URL?

**Comment by troystaylor** [comment]
When you go to your [Square Applications](https://developer.squareup.com/apps), there will be a button to open your Sandbox account:
![brave_VGzdPIwWV1](https://user-images.githubusercontent.com/44444967/189131894-62e48474-cdb2-47e9-942a-dfa7953e1afb.png)

**Comment by ThePoShWolf** [comment]
Ah, ok, I went ahead and did that and got past the previous screen.

However, now it is showing the following error again:

![image](https://user-images.githubusercontent.com/30065933/189140977-b368413c-8edd-4bee-abb7-b382ec4a013e.png)

**Comment by stanlyong** [comment]
The same issues still happening 2023-July

**Comment by jayseet** [comment]
Having the same issue here. Have tried signing out, deleting cookies etc. Once I open up the sandbox account from the developer dashboard it won't authenticate. https://squareupsandbox.com/oauth2/authorize?client_id=sq0idp-bjhfropQ5DM7gobOrHkHUA&response_type=code&redirect_uri=https%3a%2f%2fglobal.consent.azure-apim.net%2fredirect&scope=&state=c3b437fb-3f0d-4e0e-9c63-8bee0f9b4db6_canada-001_azure-apim.net
