### ISSUE TITLE
InvalidRequestContent: Could not find member 'stackOwner' on object of type 'ApiPropertiesDefinition'

### ISSUE THREAD

**Issue by YannickRe** [microsoft/PowerPlatformConnectors#614]
**Describe the bug**
I cannot create a new connector based on any of the certified connectors in this repository, as it always reports back the following response:
```
{
  "error": {
    "code": "InvalidRequestContent",
    "message": "The request content was invalid and could not be deserialized: 'Could not find member 'stackOwner' on object of type 'ApiPropertiesDefinition'. Path 'properties.stackOwner', line 1, position 1161.'."
  }
}
```

**To Reproduce**
Go into certified-connectors/Connective eSignatures, and run:
```
paconn create
```

**Expected behavior**
New connector to be created in my environment.

**Additional context**
It works when I remove `stackOwner` property from the `apiProperties.json` file. That's annoying because I'd need to remember to add it back in to submit an update to the connector.

**Comment by mamurshe** [comment]
The support for stackOwner was added in conjunction to the endpoints. Which region are you encountering this problem? For workaround please revert to an older version of paconn.

**Comment by YannickRe** [comment]
@mamurshe your docs are rather limited... How do I figure out on which version I am now? How do I revert to an older version of paconn?

In any case, my issue seems to be listed as a limitation on https://github.com/microsoft/PowerPlatformConnectors/tree/dev/tools/paconn-cli#limitations

> Stack Owner Property & apiProperties file:
> 
> Currently, there is a limitation that prevents you from updating your connector's artificats in your environment using Paconn when the stackOwner property is present in your apiProperties.json file. As a workaround to this, create two versions of your connector artifacts: the first being the version that is submitted to certification and contains the stackOwner property, the second having the stackOwner property omitted to enable updating within your environment. We are working to remove the limitation and will update this section once complete.

That README has been updated on August 5th, 2020 to add that limitation statement. Too bad that the official docs.microsoft.com article wasn't updated with this new version, it would have spared me a lot of frustration and lost time.
https://docs.microsoft.com/en-us/connectors/custom-connectors/paconn-cli?WT.mc_id=M365-MVP-5003400#limitations

**Comment by natalie-pienkowska** [comment]
@YannickRe This has been fixed :) It's available in 0.0.17

**Comment by Laskewitz** [comment]
@natalie-pienkowska I updated to 0.0.18, but the stackOwner issue is still present when using paconn create.
